name: Build and deploy application
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.3'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Build and push image
      run: |
        docker buildx build --platform linux/arm64 -t ${{ secrets.REGISTRY }}/basic-chess-ai:latest-arm64 --push .
