name: Build and deploy application
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    strategy:
      matrix:
        bot-phrases-file: [default.js, dracula.js]
        include:
        - bot-phrases-file: default.js
          image-suffix: ""
        - bot-phrases-file: dracula.js
          image-suffix: -dracula
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # See: https://github.com/orgs/community/discussions/25768#discussioncomment-3249186
    - name: Set lowercase image name env var
      run: |
        echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64/v8
        push: true
        tags: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.image-suffix }}:latest
        build-args: |
          BOT_PHRASES_URL=https://static.glob.casa/basic-chess-ai/bot-phrases/${{ matrix.bot-phrases-file }}
